repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.94.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
      exclude: "^test/fixtures/misconfigured$"
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      exclude: |
        (?x)^(
            ^examples/.*|
            ^test/fixtures/.*
        )$
