name: pr
on:
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: "**/go.sum"
      - name: Install tools
        working-directory: test
        run: |
          go install github.com/terraform-docs/terraform-docs
          go install github.com/terraform-linters/tflint

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Run terraform init
        run: |
          configs=$(find . -not -path '*/.terraform/*' -type f -name "*.tf" | xargs -I {} dirname {} | uniq)
          for config in $configs; do
            terraform -chdir=$config init -backend=false
          done

      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: "**/go.sum"

      - name: Run terratest
        working-directory: test
        run: |
          go test .

  ci:
    runs-on: ubuntu-latest
    steps:
      - run: "true"
    needs:
      - lint
      - test
